services:
    postgres:
        image: postgres:16
        container_name: careconnect_postgres
        environment:
            POSTGRES_USER: careconnect
            POSTGRES_PASSWORD: careconnect_password
            POSTGRES_DB: careconnect_db
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
